furnitureshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.ProductListView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete')
]

furnitureshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit')
]

furnitureshop/basketapp/urls.py
from django.urls import path
from basketapp.views import basket, basket_add, basket_remove, basket_edit


app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit')
]

furnitureshop/furnitureshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts


urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

furnitureshop/furnitureshop/views.py
from django.shortcuts import render
from mainapp.models import Product


def index(request):
    title = 'магазин'
    products = Product.objects.filter(category__is_active=True, is_deleted=False)[:4]
    context = {
        'title': title,
        'products': products
    }

    return render(request=request, template_name='furnitureshop/index.html', context=context)


def contacts(request):
    title = 'контакты'
    context = {
        'title': title
    }

    return render(request=request, template_name='furnitureshop/contacts.html', context=context)

furnitureshop/furnitureshop/templates/furnitureshop/includes/inc_main_menu.html
{#12 стр#}
{% load static %}

<div class="header clearfix">
    <a href="{% url 'index' %}" class="logo"><img src="{% static 'furnitureshop/img/logo.png' %}" alt=""></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}" class={% if title|title == 'Магазин' %}{{ 'active' }}{% endif %}>домой</a></li>
        <li><a href="{% url 'products:index' %}" class=
                {% if title|title == 'Продукты/Каталог' %}{{ 'active' }}{% endif %}>продукты</a></li>
        <li><a href="{% url 'contacts' %}" class=
                {% if title|title == 'Контакты' %}{{ 'active' }}{% endif %}>контакты</a></li>
        {% if user.is_superuser %}
            <li>
                <a href="{% url 'admin_staff:users' %}">Админка</a>
            </li>
        {% endif %}
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'auth:edit' %}">
                    {{ user.first_name|default:'Пользователь' }}
                </a>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">выйти</a>
            {% else %}
                <a href="{% url 'auth:login' %}">войти</a>
            {% endif %}
        </li>
    </ul>
    <a href="#" class="search"><img src="{% static 'furnitureshop/img/search.png' %}" alt=""></a>
    <a href="{% url 'basket:view' %}" class="basket"><img src="{% static 'furnitureshop/img/basket.png' %}"
                                                          alt=""><div>&nbsp{{ basket|length }}</div>
        <span>
            {% if basket %}
                {{ basket.0.total_cost|floatformat:0 }} руб
                {{ basket.0.total_quantity }} шт
            {% endif %}
        </span>
    </a>
</div>