furnitureshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp


app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.ProductListView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete')
]

furnitureshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit')
]

furnitureshop/furnitureshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts


urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('admin/', admin.site.urls),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

furnitureshop/adminapp/models.py
from django.db import models

# Create your models here.

furnitureshop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_deleted' or field_name == 'is_active':
                field.widget.attrs['class'] = 'form-check-input mt-0'
            else:
                field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_deleted':
                field.widget.attrs['class'] = 'form-check-input mt-0'
            else:
                field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

furnitureshop/adminapp/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView

from adminapp.forms import ShopUserAdminEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from django.shortcuts import get_object_or_404
from mainapp.models import Product, ProductCategory
from adminapp.forms import ProductCategoryEditForm, ProductEditForm
from django.views.generic.list import ListView


class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserListView, self).get_context_data()
        context['title'] = 'админка/пользователи'

        return context

    def get_queryset(self):
        return ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')


class UserCreateView(CreateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    template_name = 'adminapp/user_create.html'
    success_url = reverse_lazy('admin_staff:users')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserCreateView, self).get_context_data()
        context['title'] = 'пользователи/создать'

        return context


class UserUpdateView(UpdateView):
    model = ShopUser
    form_class = ShopUserAdminEditForm
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserUpdateView, self).get_context_data()
        context['title'] = 'пользователи/редактирование'

        return context


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin_staff:users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.is_deleted = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class ProductCategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategoryListView, self).get_context_data()
        context['title'] = 'админка/категории'

        return context

    def get_queryset(self):
        return ProductCategory.objects.all().order_by('name')


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    form_class = ProductCategoryEditForm
    template_name = 'adminapp/category_create.html'
    success_url = reverse_lazy('admin_staff:categories')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategoryCreateView, self).get_context_data()
        context['title'] = 'категории/создать'

        return context


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    form_class = ProductCategoryEditForm
    success_url = reverse_lazy('admin_staff:categories')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategoryUpdateView, self).get_context_data()
        context['title'] = 'категории/редактирование'

        return context


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin_staff:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.is_deleted = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


class ProductsListView(ListView, View):
    model = Product
    template_name = 'adminapp/products.html'
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductsListView, self).get_context_data()
        context['title'] = 'админка/продукт'
        context['category_pk'] = self.kwargs['pk']

        return context

    def get_queryset(self):
        category_pk = self.kwargs['pk']
        return Product.objects.filter(category__pk=category_pk)


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductEditForm
    template_name = 'adminapp/product_create.html'

    def get_success_url(self):
        return reverse('admin_staff:products', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCreateView, self).get_context_data()
        context['title'] = 'продукты/создать'
        context['category_pk'] = self.kwargs['pk']

        return context


class ProductListView(ListView):
    model = Product
    template_name = 'adminapp/product_read.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data()
        context['title'] = 'продукты/подробнее'
        context['object'] = get_object_or_404(Product, pk=self.kwargs['pk'])

        return context

    def get_queryset(self):
        return get_object_or_404(Product, pk=self.kwargs['pk'])


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    form_class = ProductEditForm

    def get_success_url(self):
        return reverse('admin_staff:products', kwargs={'pk': self.object.category.pk})

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductUpdateView, self).get_context_data()
        context['title'] = 'продукты/редактирование'

        return context


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'

    def get_success_url(self):
        return reverse('admin_staff:products', kwargs={'pk': self.object.category.pk})

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.is_deleted = True
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

furnitureshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'adminapp/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'furnitureshop/fonts/font-awesome/css/font-awesome.css' %}">
    <script src="{% static 'adminapp/script.js' %}"></script>
    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class="bx bx-menu" id="header-toggle"></i></div>
    <div class="header_img"><img src="/media/{{ user.avatar|default:'avatar-default.png' }}" alt=""></div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{% url 'index' %}" class="nav_logo">
                <i class="bx bx-layer nav_logo-icon"></i>
                <span class="nav_logo-name">Adminka</span>
            </a>
            {% include 'adminapp/includes/inc_admin_menu.html' %}
        </div>
        <a href="{% url 'auth:logout' %}" class="nav_link"><i class="bx bx-log-out nav_icon"></i>
            <span class="nav_name">Выход</span></a>
    </nav>
</div>
<div class="height-100 bg-light">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

furnitureshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Категории</h1>
            <div class="card mb-4">
                <div class="card-header">Категории продуктов</div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Имя</th>
                                <th>Редактировать</th>
                                <th>Удалить</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Имя</th>
                                <th>Редактировать</th>
                                <th>Удалить</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for category in object_list %}
                                <tr {% if category.is_deleted %} style="opacity: 0.5;" {% endif %}>
                                    <td><a href="{% url 'admin_staff:products' pk=category.id %}"
                                           style="color: dodgerblue">{{ category.name }}</a></td>
                                    <td>
                                        <a href="{% url 'admin_staff:category_update' pk=category.id %}">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </td>

                                    <td>
                                        <a {% if category.is_deleted %} class="invisible" {% endif %}href="
                                                {% url 'admin_staff:category_delete' pk=category.id %}">
                                            <i class="fa fa-times-circle"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                         <div class="pagination">
                            {% if page_obj.has_previous %}
                                <a href="?page=1">< first&nbsp;</a>
                                <a href="?page={{ page_obj.previous_page_number }}">previous&nbsp;</a>
                            {% endif %}
                            <span class="current">
                                страница {{ page_obj.number }} из
                                {{ page_obj.paginator.num_pages }}
                            </span>
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">&nbsp;next</a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">&nbsp;last ></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'adminapp:category_create' %}">
                        <button class="btn btn-success">Создать категорию</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

furnitureshop/adminapp/templates/adminapp/category_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-3 mx-auto">
        <form class="form-horizontal" action="{% url 'admin_staff:category_create' %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="Создать">
        </form>
    </div>
{% endblock %}

furnitureshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="user_delete">
        Уверены, что хотите удалить {{ object.name }}
        <b>{{ object.name|title }}</b>
        ?
        <form action="{% url 'admin_staff:category_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin_staff:categories' %}">Отмена</a>
        </button>
    </div>
{% endblock %}

furnitureshop/adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin_staff:categories'  %}">к списку категорий</a>
    </button>
{% endblock %}

furnitureshop/adminapp/templates/adminapp/product_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-3 mx-auto">
        <form class="form-horizontal" action="{% url 'admin_staff:product_create'  pk=category_pk %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="Создать">
        </form>
    </div>
{% endblock %}

furnitureshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        Осторожно! Вы точно хотите удалить продукт - {{ object.name }}
        <b>{{ object.name|title }}</b>
        ?
        <form action="{% url 'admin_staff:product_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin_staff:categories' %}">Отмена</a>
        </button>
    </div>
{% endblock %}

furnitureshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="card" style="width: 18rem;">
        <img src="{{ object.image|media_folder_products }}" class="card-img-top" alt="">
        <div class="card-body">
            <h5 class="card-title">{{ object.name }}</h5>
            <p class="card-text">{{ object.description }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Стоимость: {{ object.price }} руб.</li>
            <li class="list-group-item">На складе: {{ object.quantity }} шт.</li>
        </ul>
    </div>
{% endblock %}

furnitureshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="text-center">
            <img src="/media/{{ product.image }}" class="w-25" alt="">
        </div>
    </div>
    <div class="row">
        <form class="form-horizontal" action="{% url 'admin_staff:product_update' pk=object.pk %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin_staff:products' pk=object.category.pk %}">к продуктам</a>
        </button>
    </div>
{% endblock %}

furnitureshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Продукты</h1>
            <div class="card mb-4">
                <div class="card-header">
                    {{ category.name }}
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Название</th>
                                <th>Описание</th>
                                <th>Количество</th>
                                <th>Стоимость</th>
                                <th>Редактировать</th>
                                <th>Удалить</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Название</th>
                                <th>Описание</th>
                                <th>Количество</th>
                                <th>Стоимость</th>
                                <th>Редактировать</th>
                                <th>Удалить</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for product in object_list %}
                                <tr {% if product.is_deleted %} style="opacity: 0.5;" {% endif %}>
                                    <td><a href="{% url 'admin_staff:product_read' product.id %}"
                                           style="color: dodgerblue">{{ product.name }}</a></td>
                                    <td>{{ product.short_desk }}</td>
                                    <td>{{ product.quantity }}</td>
                                    <td>{{ product.price }}</td>
                                    <td>
                                        <a href="{% url 'admin_staff:product_update' pk=product.id %}">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a {% if product.is_deleted %} class="invisible" {% endif %}href="
                                                    {% url 'admin_staff:product_delete' pk=product.id %}">
                                            <i class="fa fa-times-circle"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="pagination">
                            {% if page_obj.has_previous %}
                                <a href="?page=1">< first&nbsp;</a>
                                <a href="?page={{ page_obj.previous_page_number }}">previous&nbsp;</a>
                            {% endif %}
                            <span class="current">
                                страница {{ page_obj.number }} из
                                {{ page_obj.paginator.num_pages }}
                            </span>
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">&nbsp;next</a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">&nbsp;last ></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'adminapp:product_create' pk=category_pk %}">
                        <button class="btn btn-success">Создать продукт</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

furnitureshop/adminapp/templates/adminapp/user_create.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="col-3 mx-auto">
        <form class="form-horizontal" action="{% url 'adminapp:user_create' %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="Создать">
        </form>
    </div>
{% endblock %}

furnitureshop/adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="user_delete">
        Уверены, что хотите удалить {{ object.username }}
        {% if object.first_name %}
            <b>{{ object.first_name|title }}</b>
            {% if object.last_name %}
                <b>{{ object.last_name|title }}</b>
            {% endif %}
        {% endif %}
        ?
        <form action="{% url 'admin_staff:user_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin_staff:users' %}">Отмена</a>
        </button>
    </div>
{% endblock %}

furnitureshop/adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin_staff:users' %}">к списку пользователей</a>
    </button>
{% endblock %}

furnitureshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Пользователи</h1>
            <div class="card mb-4">
                <div class="card-header">Пользователи</div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellpadding="0">
                            <thead>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                                <th>Вход</th>
                                <th>Удалить</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                                <th>Вход</th>
                                <th>Удалить</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for user in object_list %}
                                <tr {% if user.is_deleted %} style="opacity: 0.5;" {% endif %}>
                                    <td><a href="{% url 'admin_staff:user_update' user.id %}"
                                           style="color: dodgerblue">{{ user.username }}</a></td>
                                    <td>{{ user.first_name }}</td>
                                    <td>{{ user.last_name }}</td>
                                    <td>{{ user.email }}</td>
                                    <td class="text-center">
                                        {% if user.is_staff %}
                                            <i class="fa fa-check-circle"></i>
                                        {% else %}
                                            <i class="fa fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td class="text-center">
                                        {% if user.is_active %}
                                            <i class="fa fa-check-circle"></i>
                                        {% else %}
                                            <i class="fa fa-times-circle"></i>
                                        {% endif %}
                                    </td>
                                    <td>{{ user.last_login }}</td>
                                    <td>
                                        <a {% if user.is_deleted %} class="invisible" {% endif %}
                                                                    href="{% url 'admin_staff:user_delete' pk=user.id %}">
                                            <i class="fa fa-times-circle"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                        <div class="pagination">
                            {% if page_obj.has_previous %}
                                <a href="?page=1">< first&nbsp;</a>
                                <a href="?page={{ page_obj.previous_page_number }}">previous&nbsp;</a>
                            {% endif %}
                            <span class="current">
                            страница {{ page_obj.number }} из
                            {{ page_obj.paginator.num_pages }}
                            </span>
                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">&nbsp;next</a>
                                <a href="?page={{ page_obj.paginator.num_pages }}">&nbsp;last ></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'adminapp:user_create' %}">
                        <button class="btn btn-success">Создать пользователя</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}